"use client";

import { useEffect, useState, Suspense } from "react";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { LoadingState, ErrorState, Card } from "@culturecompass/ui";
import { fetchStory } from "@/lib/api-client";
import { getStoredModelPreset } from "@/lib/model-preset";
import type { StoryResponse } from "@culturecompass/shared";

function StoryContent() {
  const params = useParams();
  const searchParams = useSearchParams();
  const id = params.id as string;
  const placeName = searchParams.get("name") || id.replace(/-/g, " ");

  const [story, setStory] = useState<StoryResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadStory() {
      try {
        const result = await fetchStory({
          placeName,
          tone: "immersive",
          modelPreset: getStoredModelPreset(),
        });
        setStory(result);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load story.");
      } finally {
        setLoading(false);
      }
    }

    loadStory();
  }, [placeName]);

  if (loading) {
    return <LoadingState message="Weaving an immersive cultural narrative..." />;
  }

  if (error) {
    return (
      <div className="mx-auto max-w-lg">
        <ErrorState message={error} onRetry={() => window.location.reload()} />
      </div>
    );
  }

  if (!story) return null;

  return (
    <article className="mx-auto max-w-3xl space-y-8">
      <div>
        <Link
          href={`/destination/${id}?name=${encodeURIComponent(placeName)}`}
          className="text-sm text-amber-700 hover:text-amber-900"
        >
          ← Back to {placeName}
        </Link>
        <h1 className="mt-4 font-serif text-4xl font-bold text-stone-900">{story.title}</h1>
        <p className="mt-2 text-sm capitalize text-stone-500">{story.tone} narrative</p>
      </div>

      <div className="space-y-8">
        {story.sections.map((section, index) => (
          <Card key={section.heading} className="animate-fade-in" style={{ animationDelay: `${index * 100}ms` }}>
            <h2 className="font-serif text-xl font-semibold text-stone-900">{section.heading}</h2>
            <p className="mt-4 leading-relaxed text-stone-700">{section.content}</p>
          </Card>
        ))}
      </div>

      <p className="text-center text-xs text-stone-400">
        Story generated by CultureCompass AI · Powered by Gemini
      </p>
    </article>
  );
}

export default function StoryPage() {
  return (
    <Suspense fallback={<LoadingState message="Loading story..." />}>
      <StoryContent />
    </Suspense>
  );
}
